name: Deploy Admin

on:
  push:
    branches: [main]
    paths:
      - 'caviendoo-admin/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install
        working-directory: caviendoo-admin
        run: npm install

      - name: Build
        working-directory: caviendoo-admin
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

      - name: Success
        run: echo "Admin Build successful"
